import React, { Suspense, useRef } from 'react'
import { Canvas } from '@react-three/fiber'
import { Loader, useGLTF, OrbitControls, PerspectiveCamera, Stars } from '@react-three/drei'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Campsite.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere005.geometry}
        material={materials['Material.010']}
        position={[-4.36, 2.32, -16.65]}
        rotation={[-1.52, 0.36, 1.47]}
        scale={1.08}
      />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.011']} position={[7.24, 4.32, -8.63]} scale={[1.61, 1, 1]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.012']} position={[8.81, 8.89, -7.4]} rotation={[0.03, 0.37, 0.12]} scale={4.35} />
      <group position={[-10.28, 3.04, -1.62]} scale={1.01}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.014']} />
      </group>
      <group position={[14.85, 2.6, -4.37]} scale={0.83}>
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['Material.016']} />
      </group>
      <group position={[7.36, 3.04, -0.91]} rotation={[0, -1.3, 0]} scale={1.22}>
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['Material.019']} />
      </group>
      <group position={[10.74, 17.56, -13.54]} scale={5.17}>
        <mesh geometry={nodes.Sphere012.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Sphere012_1.geometry} material={materials['Material.021']} />
      </group>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials['Material.005']}
        position={[-3.75, 7.13, -7.22]}
        rotation={[0.06, 0, 0.02]}
        scale={[0.5, 0.5, 0.19]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials['Material.001']}
        position={[-2.41, 6.78, -5.64]}
        rotation={[0.06, 0, 0.02]}
        scale={[2, 1.03, 1.64]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials['Material.003']}
        position={[-2.43, 7.74, -5.15]}
        rotation={[0.06, 0, 0.02]}
        scale={[1.64, 0.15, 1.64]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials['Material.008']}
        position={[-2.47, 9.25, -2.5]}
        rotation={[-1.15, -0.02, 0.01]}
        scale={[1.7, 0.03, 0.79]}
      />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.004']} position={[-0.6, 8.37, -3.13]} rotation={[0.06, 0, 0.02]} scale={0.17} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.006']} position={[-4.29, 8.29, -3.19]} rotation={[0.06, 0, 0.02]} scale={0.13} />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials['Material.002']}
        position={[-3.13, 6.89, -7.29]}
        rotation={[0.06, 0, 0.02]}
        scale={[0.06, 0.72, 0.03]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials['Material.007']}
        position={[0.16, 6.68, -7.44]}
        rotation={[0.06, 0, 0.02]}
        scale={[0.38, 0.17, 0.16]}
      />
      <group position={[14.85, 0.23, -19.63]} scale={0.46}>
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials['Material.023']} />
      </group>
      <group position={[-14.26, 0.82, 4.97]} scale={0.46}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.024']} />
      </group>
      <group position={[14.19, 0.91, 5.44]} rotation={[0, -1.3, 0]} scale={1.22}>
        <mesh geometry={nodes.Cube007_1.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials['Material.026']} />
      </group>
      <group position={[3.86, 17.62, 8.37]} scale={5.17}>
        <mesh geometry={nodes.Sphere013.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.Sphere013_1.geometry} material={materials['Material.028']} />
      </group>
      <mesh geometry={nodes.Sphere004.geometry} material={materials['Material.990']} position={[0.21, -4.47, -6.34]} scale={[24.26, 7.74, 26.82]} />
      <group position={[6.38, 1.9, -21.26]} rotation={[0.39, 1.3, -0.44]} scale={[0.11, 0.11, 0.03]}>
        <mesh geometry={nodes.Cube029.geometry} material={materials['Material.124']} />
        <mesh geometry={nodes.Cube029_1.geometry} material={materials['Material.123']} />
        <mesh geometry={nodes.Cube029_2.geometry} material={materials['Material.125']} />
        <mesh geometry={nodes.Cube029_3.geometry} material={materials['Material.122']} />
        <mesh geometry={nodes.Cube029_4.geometry} material={materials['Material.119']} />
        <mesh geometry={nodes.Cube029_5.geometry} material={materials['Material.120']} />
        <mesh geometry={nodes.Cube029_6.geometry} material={materials['Material.118']} />
        <mesh geometry={nodes.Cube029_7.geometry} material={materials['Material.121']} />
        <mesh geometry={nodes.Cube029_8.geometry} material={materials['Material.111']} />
        <mesh geometry={nodes.Cube029_9.geometry} material={materials['Material.112']} />
        <mesh geometry={nodes.Cube029_10.geometry} material={materials['Material.110']} />
        <mesh geometry={nodes.Cube029_11.geometry} material={materials['Material.113']} />
        <mesh geometry={nodes.Cube029_12.geometry} material={materials['Material.116']} />
        <mesh geometry={nodes.Cube029_13.geometry} material={materials['Material.115']} />
        <mesh geometry={nodes.Cube029_14.geometry} material={materials['Material.117']} />
        <mesh geometry={nodes.Cube029_15.geometry} material={materials['Material.114']} />
        <mesh geometry={nodes.Cube029_16.geometry} material={materials['Material.095']} />
        <mesh geometry={nodes.Cube029_17.geometry} material={materials['Material.096']} />
        <mesh geometry={nodes.Cube029_18.geometry} material={materials['Material.094']} />
        <mesh geometry={nodes.Cube029_19.geometry} material={materials['Material.097']} />
        <mesh geometry={nodes.Cube029_20.geometry} material={materials['Material.100']} />
        <mesh geometry={nodes.Cube029_21.geometry} material={materials['Material.099']} />
        <mesh geometry={nodes.Cube029_22.geometry} material={materials['Material.101']} />
        <mesh geometry={nodes.Cube029_23.geometry} material={materials['Material.098']} />
        <mesh geometry={nodes.Cube029_24.geometry} material={materials['Material.108']} />
        <mesh geometry={nodes.Cube029_25.geometry} material={materials['Material.107']} />
        <mesh geometry={nodes.Cube029_26.geometry} material={materials['Material.109']} />
        <mesh geometry={nodes.Cube029_27.geometry} material={materials['Material.106']} />
        <mesh geometry={nodes.Cube029_28.geometry} material={materials['Material.103']} />
        <mesh geometry={nodes.Cube029_29.geometry} material={materials['Material.104']} />
        <mesh geometry={nodes.Cube029_30.geometry} material={materials['Material.102']} />
        <mesh geometry={nodes.Cube029_31.geometry} material={materials['Material.105']} />
        <mesh geometry={nodes.Cube029_32.geometry} material={materials['Material.031']} />
        <mesh geometry={nodes.Cube029_33.geometry} material={materials['Material.032']} />
        <mesh geometry={nodes.Cube029_34.geometry} material={materials['Material.030']} />
        <mesh geometry={nodes.Cube029_35.geometry} material={materials['Material.033']} />
        <mesh geometry={nodes.Cube029_36.geometry} material={materials['Material.036']} />
        <mesh geometry={nodes.Cube029_37.geometry} material={materials['Material.035']} />
        <mesh geometry={nodes.Cube029_38.geometry} material={materials['Material.037']} />
        <mesh geometry={nodes.Cube029_39.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Cube029_40.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.Cube029_41.geometry} material={materials['Material.043']} />
        <mesh geometry={nodes.Cube029_42.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Cube029_43.geometry} material={materials['Material.042']} />
        <mesh geometry={nodes.Cube029_44.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.Cube029_45.geometry} material={materials['Material.040']} />
        <mesh geometry={nodes.Cube029_46.geometry} material={materials['Material.038']} />
        <mesh geometry={nodes.Cube029_47.geometry} material={materials['Material.041']} />
        <mesh geometry={nodes.Cube029_48.geometry} material={materials['Material.060']} />
        <mesh geometry={nodes.Cube029_49.geometry} material={materials['Material.059']} />
        <mesh geometry={nodes.Cube029_50.geometry} material={materials['Material.061']} />
        <mesh geometry={nodes.Cube029_51.geometry} material={materials['Material.058']} />
        <mesh geometry={nodes.Cube029_52.geometry} material={materials['Material.055']} />
        <mesh geometry={nodes.Cube029_53.geometry} material={materials['Material.056']} />
        <mesh geometry={nodes.Cube029_54.geometry} material={materials['Material.054']} />
        <mesh geometry={nodes.Cube029_55.geometry} material={materials['Material.057']} />
        <mesh geometry={nodes.Cube029_56.geometry} material={materials['Material.047']} />
        <mesh geometry={nodes.Cube029_57.geometry} material={materials['Material.048']} />
        <mesh geometry={nodes.Cube029_58.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.Cube029_59.geometry} material={materials['Material.049']} />
        <mesh geometry={nodes.Cube029_60.geometry} material={materials['Material.052']} />
        <mesh geometry={nodes.Cube029_61.geometry} material={materials['Material.051']} />
        <mesh geometry={nodes.Cube029_62.geometry} material={materials['Material.053']} />
        <mesh geometry={nodes.Cube029_63.geometry} material={materials['Material.050']} />
        <mesh geometry={nodes.Cube029_64.geometry} material={materials['Material.092']} />
        <mesh geometry={nodes.Cube029_65.geometry} material={materials['Material.091']} />
        <mesh geometry={nodes.Cube029_66.geometry} material={materials['Material.093']} />
        <mesh geometry={nodes.Cube029_67.geometry} material={materials['Material.090']} />
        <mesh geometry={nodes.Cube029_68.geometry} material={materials['Material.087']} />
        <mesh geometry={nodes.Cube029_69.geometry} material={materials['Material.088']} />
        <mesh geometry={nodes.Cube029_70.geometry} material={materials['Material.086']} />
        <mesh geometry={nodes.Cube029_71.geometry} material={materials['Material.089']} />
        <mesh geometry={nodes.Cube029_72.geometry} material={materials['Material.079']} />
        <mesh geometry={nodes.Cube029_73.geometry} material={materials['Material.080']} />
        <mesh geometry={nodes.Cube029_74.geometry} material={materials['Material.078']} />
        <mesh geometry={nodes.Cube029_75.geometry} material={materials['Material.081']} />
        <mesh geometry={nodes.Cube029_76.geometry} material={materials['Material.084']} />
        <mesh geometry={nodes.Cube029_77.geometry} material={materials['Material.083']} />
        <mesh geometry={nodes.Cube029_78.geometry} material={materials['Material.085']} />
        <mesh geometry={nodes.Cube029_79.geometry} material={materials['Material.082']} />
        <mesh geometry={nodes.Cube029_80.geometry} material={materials['Material.063']} />
        <mesh geometry={nodes.Cube029_81.geometry} material={materials['Material.064']} />
        <mesh geometry={nodes.Cube029_82.geometry} material={materials['Material.062']} />
        <mesh geometry={nodes.Cube029_83.geometry} material={materials['Material.065']} />
        <mesh geometry={nodes.Cube029_84.geometry} material={materials['Material.068']} />
        <mesh geometry={nodes.Cube029_85.geometry} material={materials['Material.067']} />
        <mesh geometry={nodes.Cube029_86.geometry} material={materials['Material.069']} />
        <mesh geometry={nodes.Cube029_87.geometry} material={materials['Material.066']} />
        <mesh geometry={nodes.Cube029_88.geometry} material={materials['Material.076']} />
        <mesh geometry={nodes.Cube029_89.geometry} material={materials['Material.075']} />
        <mesh geometry={nodes.Cube029_90.geometry} material={materials['Material.077']} />
        <mesh geometry={nodes.Cube029_91.geometry} material={materials['Material.074']} />
        <mesh geometry={nodes.Cube029_92.geometry} material={materials['Material.071']} />
        <mesh geometry={nodes.Cube029_93.geometry} material={materials['Material.072']} />
        <mesh geometry={nodes.Cube029_94.geometry} material={materials['Material.070']} />
        <mesh geometry={nodes.Cube029_95.geometry} material={materials['Material.073']} />
        <mesh geometry={nodes.Cube029_96.geometry} material={materials['Material.127']} />
        <mesh geometry={nodes.Cube029_97.geometry} material={materials['Material.128']} />
        <mesh geometry={nodes.Cube029_98.geometry} material={materials['Material.126']} />
        <mesh geometry={nodes.Cube029_99.geometry} material={materials['Material.129']} />
        <mesh geometry={nodes.Cube029_100.geometry} material={materials['Material.132']} />
        <mesh geometry={nodes.Cube029_101.geometry} material={materials['Material.131']} />
        <mesh geometry={nodes.Cube029_102.geometry} material={materials['Material.133']} />
        <mesh geometry={nodes.Cube029_103.geometry} material={materials['Material.130']} />
        <mesh geometry={nodes.Cube029_104.geometry} material={materials['Material.140']} />
        <mesh geometry={nodes.Cube029_105.geometry} material={materials['Material.139']} />
        <mesh geometry={nodes.Cube029_106.geometry} material={materials['Material.141']} />
        <mesh geometry={nodes.Cube029_107.geometry} material={materials['Material.138']} />
        <mesh geometry={nodes.Cube029_108.geometry} material={materials['Material.135']} />
        <mesh geometry={nodes.Cube029_109.geometry} material={materials['Material.136']} />
        <mesh geometry={nodes.Cube029_110.geometry} material={materials['Material.134']} />
        <mesh geometry={nodes.Cube029_111.geometry} material={materials['Material.137']} />
        <mesh geometry={nodes.Cube029_112.geometry} material={materials['Material.156']} />
        <mesh geometry={nodes.Cube029_113.geometry} material={materials['Material.155']} />
        <mesh geometry={nodes.Cube029_114.geometry} material={materials['Material.157']} />
        <mesh geometry={nodes.Cube029_115.geometry} material={materials['Material.154']} />
        <mesh geometry={nodes.Cube029_116.geometry} material={materials['Material.151']} />
        <mesh geometry={nodes.Cube029_117.geometry} material={materials['Material.152']} />
        <mesh geometry={nodes.Cube029_118.geometry} material={materials['Material.150']} />
        <mesh geometry={nodes.Cube029_119.geometry} material={materials['Material.153']} />
        <mesh geometry={nodes.Cube029_120.geometry} material={materials['Material.143']} />
        <mesh geometry={nodes.Cube029_121.geometry} material={materials['Material.144']} />
        <mesh geometry={nodes.Cube029_122.geometry} material={materials['Material.142']} />
        <mesh geometry={nodes.Cube029_123.geometry} material={materials['Material.145']} />
        <mesh geometry={nodes.Cube029_124.geometry} material={materials['Material.148']} />
        <mesh geometry={nodes.Cube029_125.geometry} material={materials['Material.147']} />
        <mesh geometry={nodes.Cube029_126.geometry} material={materials['Material.149']} />
        <mesh geometry={nodes.Cube029_127.geometry} material={materials['Material.146']} />
        <mesh geometry={nodes.Cube029_128.geometry} material={materials['Material.220']} />
        <mesh geometry={nodes.Cube029_129.geometry} material={materials['Material.219']} />
        <mesh geometry={nodes.Cube029_130.geometry} material={materials['Material.221']} />
        <mesh geometry={nodes.Cube029_131.geometry} material={materials['Material.218']} />
        <mesh geometry={nodes.Cube029_132.geometry} material={materials['Material.215']} />
        <mesh geometry={nodes.Cube029_133.geometry} material={materials['Material.216']} />
        <mesh geometry={nodes.Cube029_134.geometry} material={materials['Material.214']} />
        <mesh geometry={nodes.Cube029_135.geometry} material={materials['Material.217']} />
        <mesh geometry={nodes.Cube029_136.geometry} material={materials['Material.207']} />
        <mesh geometry={nodes.Cube029_137.geometry} material={materials['Material.208']} />
        <mesh geometry={nodes.Cube029_138.geometry} material={materials['Material.206']} />
        <mesh geometry={nodes.Cube029_139.geometry} material={materials['Material.209']} />
        <mesh geometry={nodes.Cube029_140.geometry} material={materials['Material.212']} />
        <mesh geometry={nodes.Cube029_141.geometry} material={materials['Material.211']} />
        <mesh geometry={nodes.Cube029_142.geometry} material={materials['Material.213']} />
        <mesh geometry={nodes.Cube029_143.geometry} material={materials['Material.210']} />
        <mesh geometry={nodes.Cube029_144.geometry} material={materials['Material.191']} />
        <mesh geometry={nodes.Cube029_145.geometry} material={materials['Material.192']} />
        <mesh geometry={nodes.Cube029_146.geometry} material={materials['Material.190']} />
        <mesh geometry={nodes.Cube029_147.geometry} material={materials['Material.193']} />
        <mesh geometry={nodes.Cube029_148.geometry} material={materials['Material.196']} />
        <mesh geometry={nodes.Cube029_149.geometry} material={materials['Material.195']} />
        <mesh geometry={nodes.Cube029_150.geometry} material={materials['Material.197']} />
        <mesh geometry={nodes.Cube029_151.geometry} material={materials['Material.194']} />
        <mesh geometry={nodes.Cube029_152.geometry} material={materials['Material.204']} />
        <mesh geometry={nodes.Cube029_153.geometry} material={materials['Material.203']} />
        <mesh geometry={nodes.Cube029_154.geometry} material={materials['Material.205']} />
        <mesh geometry={nodes.Cube029_155.geometry} material={materials['Material.202']} />
        <mesh geometry={nodes.Cube029_156.geometry} material={materials['Material.199']} />
        <mesh geometry={nodes.Cube029_157.geometry} material={materials['Material.200']} />
        <mesh geometry={nodes.Cube029_158.geometry} material={materials['Material.198']} />
        <mesh geometry={nodes.Cube029_159.geometry} material={materials['Material.201']} />
        <mesh geometry={nodes.Cube029_160.geometry} material={materials['Material.159']} />
        <mesh geometry={nodes.Cube029_161.geometry} material={materials['Material.160']} />
        <mesh geometry={nodes.Cube029_162.geometry} material={materials['Material.158']} />
        <mesh geometry={nodes.Cube029_163.geometry} material={materials['Material.161']} />
        <mesh geometry={nodes.Cube029_164.geometry} material={materials['Material.164']} />
        <mesh geometry={nodes.Cube029_165.geometry} material={materials['Material.163']} />
        <mesh geometry={nodes.Cube029_166.geometry} material={materials['Material.165']} />
        <mesh geometry={nodes.Cube029_167.geometry} material={materials['Material.162']} />
        <mesh geometry={nodes.Cube029_168.geometry} material={materials['Material.172']} />
        <mesh geometry={nodes.Cube029_169.geometry} material={materials['Material.171']} />
        <mesh geometry={nodes.Cube029_170.geometry} material={materials['Material.173']} />
        <mesh geometry={nodes.Cube029_171.geometry} material={materials['Material.170']} />
        <mesh geometry={nodes.Cube029_172.geometry} material={materials['Material.167']} />
        <mesh geometry={nodes.Cube029_173.geometry} material={materials['Material.168']} />
        <mesh geometry={nodes.Cube029_174.geometry} material={materials['Material.166']} />
        <mesh geometry={nodes.Cube029_175.geometry} material={materials['Material.169']} />
        <mesh geometry={nodes.Cube029_176.geometry} material={materials['Material.188']} />
        <mesh geometry={nodes.Cube029_177.geometry} material={materials['Material.187']} />
        <mesh geometry={nodes.Cube029_178.geometry} material={materials['Material.189']} />
        <mesh geometry={nodes.Cube029_179.geometry} material={materials['Material.186']} />
        <mesh geometry={nodes.Cube029_180.geometry} material={materials['Material.183']} />
        <mesh geometry={nodes.Cube029_181.geometry} material={materials['Material.184']} />
        <mesh geometry={nodes.Cube029_182.geometry} material={materials['Material.182']} />
        <mesh geometry={nodes.Cube029_183.geometry} material={materials['Material.185']} />
        <mesh geometry={nodes.Cube029_184.geometry} material={materials['Material.175']} />
        <mesh geometry={nodes.Cube029_185.geometry} material={materials['Material.176']} />
        <mesh geometry={nodes.Cube029_186.geometry} material={materials['Material.174']} />
        <mesh geometry={nodes.Cube029_187.geometry} material={materials['Material.177']} />
        <mesh geometry={nodes.Cube029_188.geometry} material={materials['Material.180']} />
        <mesh geometry={nodes.Cube029_189.geometry} material={materials['Material.179']} />
        <mesh geometry={nodes.Cube029_190.geometry} material={materials['Material.181']} />
        <mesh geometry={nodes.Cube029_191.geometry} material={materials['Material.178']} />
      </group>
      <group position={[14.1, 2.14, -8.63]} rotation={[0.92, 1.27, -0.81]} scale={[0.11, 0.11, 0.03]}>
        <mesh geometry={nodes.Cube031.geometry} material={materials['Material.319']} />
        <mesh geometry={nodes.Cube031_1.geometry} material={materials['Material.320']} />
        <mesh geometry={nodes.Cube031_2.geometry} material={materials['Material.318']} />
        <mesh geometry={nodes.Cube031_3.geometry} material={materials['Material.321']} />
        <mesh geometry={nodes.Cube031_4.geometry} material={materials['Material.324']} />
        <mesh geometry={nodes.Cube031_5.geometry} material={materials['Material.323']} />
        <mesh geometry={nodes.Cube031_6.geometry} material={materials['Material.325']} />
        <mesh geometry={nodes.Cube031_7.geometry} material={materials['Material.322']} />
        <mesh geometry={nodes.Cube031_8.geometry} material={materials['Material.332']} />
        <mesh geometry={nodes.Cube031_9.geometry} material={materials['Material.331']} />
        <mesh geometry={nodes.Cube031_10.geometry} material={materials['Material.333']} />
        <mesh geometry={nodes.Cube031_11.geometry} material={materials['Material.330']} />
        <mesh geometry={nodes.Cube031_12.geometry} material={materials['Material.327']} />
        <mesh geometry={nodes.Cube031_13.geometry} material={materials['Material.328']} />
        <mesh geometry={nodes.Cube031_14.geometry} material={materials['Material.326']} />
        <mesh geometry={nodes.Cube031_15.geometry} material={materials['Material.329']} />
        <mesh geometry={nodes.Cube031_16.geometry} material={materials['Material.348']} />
        <mesh geometry={nodes.Cube031_17.geometry} material={materials['Material.347']} />
        <mesh geometry={nodes.Cube031_18.geometry} material={materials['Material.349']} />
        <mesh geometry={nodes.Cube031_19.geometry} material={materials['Material.346']} />
        <mesh geometry={nodes.Cube031_20.geometry} material={materials['Material.343']} />
        <mesh geometry={nodes.Cube031_21.geometry} material={materials['Material.344']} />
        <mesh geometry={nodes.Cube031_22.geometry} material={materials['Material.342']} />
        <mesh geometry={nodes.Cube031_23.geometry} material={materials['Material.345']} />
        <mesh geometry={nodes.Cube031_24.geometry} material={materials['Material.335']} />
        <mesh geometry={nodes.Cube031_25.geometry} material={materials['Material.336']} />
        <mesh geometry={nodes.Cube031_26.geometry} material={materials['Material.334']} />
        <mesh geometry={nodes.Cube031_27.geometry} material={materials['Material.337']} />
        <mesh geometry={nodes.Cube031_28.geometry} material={materials['Material.340']} />
        <mesh geometry={nodes.Cube031_29.geometry} material={materials['Material.339']} />
        <mesh geometry={nodes.Cube031_30.geometry} material={materials['Material.341']} />
        <mesh geometry={nodes.Cube031_31.geometry} material={materials['Material.338']} />
        <mesh geometry={nodes.Cube031_32.geometry} material={materials['Material.412']} />
        <mesh geometry={nodes.Cube031_33.geometry} material={materials['Material.411']} />
        <mesh geometry={nodes.Cube031_34.geometry} material={materials['Material.413']} />
        <mesh geometry={nodes.Cube031_35.geometry} material={materials['Material.410']} />
        <mesh geometry={nodes.Cube031_36.geometry} material={materials['Material.407']} />
        <mesh geometry={nodes.Cube031_37.geometry} material={materials['Material.408']} />
        <mesh geometry={nodes.Cube031_38.geometry} material={materials['Material.406']} />
        <mesh geometry={nodes.Cube031_39.geometry} material={materials['Material.409']} />
        <mesh geometry={nodes.Cube031_40.geometry} material={materials['Material.399']} />
        <mesh geometry={nodes.Cube031_41.geometry} material={materials['Material.400']} />
        <mesh geometry={nodes.Cube031_42.geometry} material={materials['Material.398']} />
        <mesh geometry={nodes.Cube031_43.geometry} material={materials['Material.401']} />
        <mesh geometry={nodes.Cube031_44.geometry} material={materials['Material.404']} />
        <mesh geometry={nodes.Cube031_45.geometry} material={materials['Material.403']} />
        <mesh geometry={nodes.Cube031_46.geometry} material={materials['Material.405']} />
        <mesh geometry={nodes.Cube031_47.geometry} material={materials['Material.402']} />
        <mesh geometry={nodes.Cube031_48.geometry} material={materials['Material.383']} />
        <mesh geometry={nodes.Cube031_49.geometry} material={materials['Material.384']} />
        <mesh geometry={nodes.Cube031_50.geometry} material={materials['Material.382']} />
        <mesh geometry={nodes.Cube031_51.geometry} material={materials['Material.385']} />
        <mesh geometry={nodes.Cube031_52.geometry} material={materials['Material.388']} />
        <mesh geometry={nodes.Cube031_53.geometry} material={materials['Material.387']} />
        <mesh geometry={nodes.Cube031_54.geometry} material={materials['Material.389']} />
        <mesh geometry={nodes.Cube031_55.geometry} material={materials['Material.386']} />
        <mesh geometry={nodes.Cube031_56.geometry} material={materials['Material.396']} />
        <mesh geometry={nodes.Cube031_57.geometry} material={materials['Material.395']} />
        <mesh geometry={nodes.Cube031_58.geometry} material={materials['Material.397']} />
        <mesh geometry={nodes.Cube031_59.geometry} material={materials['Material.394']} />
        <mesh geometry={nodes.Cube031_60.geometry} material={materials['Material.391']} />
        <mesh geometry={nodes.Cube031_61.geometry} material={materials['Material.392']} />
        <mesh geometry={nodes.Cube031_62.geometry} material={materials['Material.390']} />
        <mesh geometry={nodes.Cube031_63.geometry} material={materials['Material.393']} />
        <mesh geometry={nodes.Cube031_64.geometry} material={materials['Material.351']} />
        <mesh geometry={nodes.Cube031_65.geometry} material={materials['Material.352']} />
        <mesh geometry={nodes.Cube031_66.geometry} material={materials['Material.350']} />
        <mesh geometry={nodes.Cube031_67.geometry} material={materials['Material.353']} />
        <mesh geometry={nodes.Cube031_68.geometry} material={materials['Material.356']} />
        <mesh geometry={nodes.Cube031_69.geometry} material={materials['Material.355']} />
        <mesh geometry={nodes.Cube031_70.geometry} material={materials['Material.357']} />
        <mesh geometry={nodes.Cube031_71.geometry} material={materials['Material.354']} />
        <mesh geometry={nodes.Cube031_72.geometry} material={materials['Material.364']} />
        <mesh geometry={nodes.Cube031_73.geometry} material={materials['Material.363']} />
        <mesh geometry={nodes.Cube031_74.geometry} material={materials['Material.365']} />
        <mesh geometry={nodes.Cube031_75.geometry} material={materials['Material.362']} />
        <mesh geometry={nodes.Cube031_76.geometry} material={materials['Material.359']} />
        <mesh geometry={nodes.Cube031_77.geometry} material={materials['Material.360']} />
        <mesh geometry={nodes.Cube031_78.geometry} material={materials['Material.358']} />
        <mesh geometry={nodes.Cube031_79.geometry} material={materials['Material.361']} />
        <mesh geometry={nodes.Cube031_80.geometry} material={materials['Material.380']} />
        <mesh geometry={nodes.Cube031_81.geometry} material={materials['Material.379']} />
        <mesh geometry={nodes.Cube031_82.geometry} material={materials['Material.381']} />
        <mesh geometry={nodes.Cube031_83.geometry} material={materials['Material.378']} />
        <mesh geometry={nodes.Cube031_84.geometry} material={materials['Material.375']} />
        <mesh geometry={nodes.Cube031_85.geometry} material={materials['Material.376']} />
        <mesh geometry={nodes.Cube031_86.geometry} material={materials['Material.374']} />
        <mesh geometry={nodes.Cube031_87.geometry} material={materials['Material.377']} />
        <mesh geometry={nodes.Cube031_88.geometry} material={materials['Material.367']} />
        <mesh geometry={nodes.Cube031_89.geometry} material={materials['Material.368']} />
        <mesh geometry={nodes.Cube031_90.geometry} material={materials['Material.366']} />
        <mesh geometry={nodes.Cube031_91.geometry} material={materials['Material.369']} />
        <mesh geometry={nodes.Cube031_92.geometry} material={materials['Material.372']} />
        <mesh geometry={nodes.Cube031_93.geometry} material={materials['Material.371']} />
        <mesh geometry={nodes.Cube031_94.geometry} material={materials['Material.373']} />
        <mesh geometry={nodes.Cube031_95.geometry} material={materials['Material.370']} />
        <mesh geometry={nodes.Cube031_96.geometry} material={materials['Material.316']} />
        <mesh geometry={nodes.Cube031_97.geometry} material={materials['Material.315']} />
        <mesh geometry={nodes.Cube031_98.geometry} material={materials['Material.317']} />
        <mesh geometry={nodes.Cube031_99.geometry} material={materials['Material.314']} />
        <mesh geometry={nodes.Cube031_100.geometry} material={materials['Material.311']} />
        <mesh geometry={nodes.Cube031_101.geometry} material={materials['Material.312']} />
        <mesh geometry={nodes.Cube031_102.geometry} material={materials['Material.310']} />
        <mesh geometry={nodes.Cube031_103.geometry} material={materials['Material.313']} />
        <mesh geometry={nodes.Cube031_104.geometry} material={materials['Material.303']} />
        <mesh geometry={nodes.Cube031_105.geometry} material={materials['Material.304']} />
        <mesh geometry={nodes.Cube031_106.geometry} material={materials['Material.302']} />
        <mesh geometry={nodes.Cube031_107.geometry} material={materials['Material.305']} />
        <mesh geometry={nodes.Cube031_108.geometry} material={materials['Material.308']} />
        <mesh geometry={nodes.Cube031_109.geometry} material={materials['Material.307']} />
        <mesh geometry={nodes.Cube031_110.geometry} material={materials['Material.309']} />
        <mesh geometry={nodes.Cube031_111.geometry} material={materials['Material.306']} />
        <mesh geometry={nodes.Cube031_112.geometry} material={materials['Material.287']} />
        <mesh geometry={nodes.Cube031_113.geometry} material={materials['Material.288']} />
        <mesh geometry={nodes.Cube031_114.geometry} material={materials['Material.286']} />
        <mesh geometry={nodes.Cube031_115.geometry} material={materials['Material.289']} />
        <mesh geometry={nodes.Cube031_116.geometry} material={materials['Material.292']} />
        <mesh geometry={nodes.Cube031_117.geometry} material={materials['Material.291']} />
        <mesh geometry={nodes.Cube031_118.geometry} material={materials['Material.293']} />
        <mesh geometry={nodes.Cube031_119.geometry} material={materials['Material.290']} />
        <mesh geometry={nodes.Cube031_120.geometry} material={materials['Material.300']} />
        <mesh geometry={nodes.Cube031_121.geometry} material={materials['Material.299']} />
        <mesh geometry={nodes.Cube031_122.geometry} material={materials['Material.301']} />
        <mesh geometry={nodes.Cube031_123.geometry} material={materials['Material.298']} />
        <mesh geometry={nodes.Cube031_124.geometry} material={materials['Material.295']} />
        <mesh geometry={nodes.Cube031_125.geometry} material={materials['Material.296']} />
        <mesh geometry={nodes.Cube031_126.geometry} material={materials['Material.294']} />
        <mesh geometry={nodes.Cube031_127.geometry} material={materials['Material.297']} />
        <mesh geometry={nodes.Cube031_128.geometry} material={materials['Material.223']} />
        <mesh geometry={nodes.Cube031_129.geometry} material={materials['Material.224']} />
        <mesh geometry={nodes.Cube031_130.geometry} material={materials['Material.222']} />
        <mesh geometry={nodes.Cube031_131.geometry} material={materials['Material.225']} />
        <mesh geometry={nodes.Cube031_132.geometry} material={materials['Material.228']} />
        <mesh geometry={nodes.Cube031_133.geometry} material={materials['Material.227']} />
        <mesh geometry={nodes.Cube031_134.geometry} material={materials['Material.229']} />
        <mesh geometry={nodes.Cube031_135.geometry} material={materials['Material.226']} />
        <mesh geometry={nodes.Cube031_136.geometry} material={materials['Material.236']} />
        <mesh geometry={nodes.Cube031_137.geometry} material={materials['Material.235']} />
        <mesh geometry={nodes.Cube031_138.geometry} material={materials['Material.237']} />
        <mesh geometry={nodes.Cube031_139.geometry} material={materials['Material.234']} />
        <mesh geometry={nodes.Cube031_140.geometry} material={materials['Material.231']} />
        <mesh geometry={nodes.Cube031_141.geometry} material={materials['Material.232']} />
        <mesh geometry={nodes.Cube031_142.geometry} material={materials['Material.230']} />
        <mesh geometry={nodes.Cube031_143.geometry} material={materials['Material.233']} />
        <mesh geometry={nodes.Cube031_144.geometry} material={materials['Material.252']} />
        <mesh geometry={nodes.Cube031_145.geometry} material={materials['Material.251']} />
        <mesh geometry={nodes.Cube031_146.geometry} material={materials['Material.253']} />
        <mesh geometry={nodes.Cube031_147.geometry} material={materials['Material.250']} />
        <mesh geometry={nodes.Cube031_148.geometry} material={materials['Material.247']} />
        <mesh geometry={nodes.Cube031_149.geometry} material={materials['Material.248']} />
        <mesh geometry={nodes.Cube031_150.geometry} material={materials['Material.246']} />
        <mesh geometry={nodes.Cube031_151.geometry} material={materials['Material.249']} />
        <mesh geometry={nodes.Cube031_152.geometry} material={materials['Material.239']} />
        <mesh geometry={nodes.Cube031_153.geometry} material={materials['Material.240']} />
        <mesh geometry={nodes.Cube031_154.geometry} material={materials['Material.238']} />
        <mesh geometry={nodes.Cube031_155.geometry} material={materials['Material.241']} />
        <mesh geometry={nodes.Cube031_156.geometry} material={materials['Material.244']} />
        <mesh geometry={nodes.Cube031_157.geometry} material={materials['Material.243']} />
        <mesh geometry={nodes.Cube031_158.geometry} material={materials['Material.245']} />
        <mesh geometry={nodes.Cube031_159.geometry} material={materials['Material.242']} />
        <mesh geometry={nodes.Cube031_160.geometry} material={materials['Material.284']} />
        <mesh geometry={nodes.Cube031_161.geometry} material={materials['Material.283']} />
        <mesh geometry={nodes.Cube031_162.geometry} material={materials['Material.285']} />
        <mesh geometry={nodes.Cube031_163.geometry} material={materials['Material.282']} />
        <mesh geometry={nodes.Cube031_164.geometry} material={materials['Material.279']} />
        <mesh geometry={nodes.Cube031_165.geometry} material={materials['Material.280']} />
        <mesh geometry={nodes.Cube031_166.geometry} material={materials['Material.278']} />
        <mesh geometry={nodes.Cube031_167.geometry} material={materials['Material.281']} />
        <mesh geometry={nodes.Cube031_168.geometry} material={materials['Material.271']} />
        <mesh geometry={nodes.Cube031_169.geometry} material={materials['Material.272']} />
        <mesh geometry={nodes.Cube031_170.geometry} material={materials['Material.270']} />
        <mesh geometry={nodes.Cube031_171.geometry} material={materials['Material.273']} />
        <mesh geometry={nodes.Cube031_172.geometry} material={materials['Material.276']} />
        <mesh geometry={nodes.Cube031_173.geometry} material={materials['Material.275']} />
        <mesh geometry={nodes.Cube031_174.geometry} material={materials['Material.277']} />
        <mesh geometry={nodes.Cube031_175.geometry} material={materials['Material.274']} />
        <mesh geometry={nodes.Cube031_176.geometry} material={materials['Material.255']} />
        <mesh geometry={nodes.Cube031_177.geometry} material={materials['Material.256']} />
        <mesh geometry={nodes.Cube031_178.geometry} material={materials['Material.254']} />
        <mesh geometry={nodes.Cube031_179.geometry} material={materials['Material.257']} />
        <mesh geometry={nodes.Cube031_180.geometry} material={materials['Material.260']} />
        <mesh geometry={nodes.Cube031_181.geometry} material={materials['Material.259']} />
        <mesh geometry={nodes.Cube031_182.geometry} material={materials['Material.261']} />
        <mesh geometry={nodes.Cube031_183.geometry} material={materials['Material.258']} />
        <mesh geometry={nodes.Cube031_184.geometry} material={materials['Material.268']} />
        <mesh geometry={nodes.Cube031_185.geometry} material={materials['Material.267']} />
        <mesh geometry={nodes.Cube031_186.geometry} material={materials['Material.269']} />
        <mesh geometry={nodes.Cube031_187.geometry} material={materials['Material.266']} />
        <mesh geometry={nodes.Cube031_188.geometry} material={materials['Material.263']} />
        <mesh geometry={nodes.Cube031_189.geometry} material={materials['Material.264']} />
        <mesh geometry={nodes.Cube031_190.geometry} material={materials['Material.262']} />
        <mesh geometry={nodes.Cube031_191.geometry} material={materials['Material.265']} />
      </group>
      <group position={[-12.47, 1.96, -13.58]} rotation={[2.77, -1.02, 2.94]} scale={[0.11, 0.11, 0.03]}>
        <mesh geometry={nodes.Cube032.geometry} material={materials['Material.511']} />
        <mesh geometry={nodes.Cube032_1.geometry} material={materials['Material.512']} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Material.510']} />
        <mesh geometry={nodes.Cube032_3.geometry} material={materials['Material.513']} />
        <mesh geometry={nodes.Cube032_4.geometry} material={materials['Material.516']} />
        <mesh geometry={nodes.Cube032_5.geometry} material={materials['Material.515']} />
        <mesh geometry={nodes.Cube032_6.geometry} material={materials['Material.517']} />
        <mesh geometry={nodes.Cube032_7.geometry} material={materials['Material.514']} />
        <mesh geometry={nodes.Cube032_8.geometry} material={materials['Material.524']} />
        <mesh geometry={nodes.Cube032_9.geometry} material={materials['Material.523']} />
        <mesh geometry={nodes.Cube032_10.geometry} material={materials['Material.525']} />
        <mesh geometry={nodes.Cube032_11.geometry} material={materials['Material.522']} />
        <mesh geometry={nodes.Cube032_12.geometry} material={materials['Material.519']} />
        <mesh geometry={nodes.Cube032_13.geometry} material={materials['Material.520']} />
        <mesh geometry={nodes.Cube032_14.geometry} material={materials['Material.518']} />
        <mesh geometry={nodes.Cube032_15.geometry} material={materials['Material.521']} />
        <mesh geometry={nodes.Cube032_16.geometry} material={materials['Material.540']} />
        <mesh geometry={nodes.Cube032_17.geometry} material={materials['Material.539']} />
        <mesh geometry={nodes.Cube032_18.geometry} material={materials['Material.541']} />
        <mesh geometry={nodes.Cube032_19.geometry} material={materials['Material.538']} />
        <mesh geometry={nodes.Cube032_20.geometry} material={materials['Material.535']} />
        <mesh geometry={nodes.Cube032_21.geometry} material={materials['Material.536']} />
        <mesh geometry={nodes.Cube032_22.geometry} material={materials['Material.534']} />
        <mesh geometry={nodes.Cube032_23.geometry} material={materials['Material.537']} />
        <mesh geometry={nodes.Cube032_24.geometry} material={materials['Material.527']} />
        <mesh geometry={nodes.Cube032_25.geometry} material={materials['Material.528']} />
        <mesh geometry={nodes.Cube032_26.geometry} material={materials['Material.526']} />
        <mesh geometry={nodes.Cube032_27.geometry} material={materials['Material.529']} />
        <mesh geometry={nodes.Cube032_28.geometry} material={materials['Material.532']} />
        <mesh geometry={nodes.Cube032_29.geometry} material={materials['Material.531']} />
        <mesh geometry={nodes.Cube032_30.geometry} material={materials['Material.533']} />
        <mesh geometry={nodes.Cube032_31.geometry} material={materials['Material.530']} />
        <mesh geometry={nodes.Cube032_32.geometry} material={materials['Material.604']} />
        <mesh geometry={nodes.Cube032_33.geometry} material={materials['Material.603']} />
        <mesh geometry={nodes.Cube032_34.geometry} material={materials['Material.605']} />
        <mesh geometry={nodes.Cube032_35.geometry} material={materials['Material.602']} />
        <mesh geometry={nodes.Cube032_36.geometry} material={materials['Material.599']} />
        <mesh geometry={nodes.Cube032_37.geometry} material={materials['Material.600']} />
        <mesh geometry={nodes.Cube032_38.geometry} material={materials['Material.598']} />
        <mesh geometry={nodes.Cube032_39.geometry} material={materials['Material.601']} />
        <mesh geometry={nodes.Cube032_40.geometry} material={materials['Material.591']} />
        <mesh geometry={nodes.Cube032_41.geometry} material={materials['Material.592']} />
        <mesh geometry={nodes.Cube032_42.geometry} material={materials['Material.590']} />
        <mesh geometry={nodes.Cube032_43.geometry} material={materials['Material.593']} />
        <mesh geometry={nodes.Cube032_44.geometry} material={materials['Material.596']} />
        <mesh geometry={nodes.Cube032_45.geometry} material={materials['Material.595']} />
        <mesh geometry={nodes.Cube032_46.geometry} material={materials['Material.597']} />
        <mesh geometry={nodes.Cube032_47.geometry} material={materials['Material.594']} />
        <mesh geometry={nodes.Cube032_48.geometry} material={materials['Material.575']} />
        <mesh geometry={nodes.Cube032_49.geometry} material={materials['Material.576']} />
        <mesh geometry={nodes.Cube032_50.geometry} material={materials['Material.574']} />
        <mesh geometry={nodes.Cube032_51.geometry} material={materials['Material.577']} />
        <mesh geometry={nodes.Cube032_52.geometry} material={materials['Material.580']} />
        <mesh geometry={nodes.Cube032_53.geometry} material={materials['Material.579']} />
        <mesh geometry={nodes.Cube032_54.geometry} material={materials['Material.581']} />
        <mesh geometry={nodes.Cube032_55.geometry} material={materials['Material.578']} />
        <mesh geometry={nodes.Cube032_56.geometry} material={materials['Material.588']} />
        <mesh geometry={nodes.Cube032_57.geometry} material={materials['Material.587']} />
        <mesh geometry={nodes.Cube032_58.geometry} material={materials['Material.589']} />
        <mesh geometry={nodes.Cube032_59.geometry} material={materials['Material.586']} />
        <mesh geometry={nodes.Cube032_60.geometry} material={materials['Material.583']} />
        <mesh geometry={nodes.Cube032_61.geometry} material={materials['Material.584']} />
        <mesh geometry={nodes.Cube032_62.geometry} material={materials['Material.582']} />
        <mesh geometry={nodes.Cube032_63.geometry} material={materials['Material.585']} />
        <mesh geometry={nodes.Cube032_64.geometry} material={materials['Material.543']} />
        <mesh geometry={nodes.Cube032_65.geometry} material={materials['Material.544']} />
        <mesh geometry={nodes.Cube032_66.geometry} material={materials['Material.542']} />
        <mesh geometry={nodes.Cube032_67.geometry} material={materials['Material.545']} />
        <mesh geometry={nodes.Cube032_68.geometry} material={materials['Material.548']} />
        <mesh geometry={nodes.Cube032_69.geometry} material={materials['Material.547']} />
        <mesh geometry={nodes.Cube032_70.geometry} material={materials['Material.549']} />
        <mesh geometry={nodes.Cube032_71.geometry} material={materials['Material.546']} />
        <mesh geometry={nodes.Cube032_72.geometry} material={materials['Material.556']} />
        <mesh geometry={nodes.Cube032_73.geometry} material={materials['Material.555']} />
        <mesh geometry={nodes.Cube032_74.geometry} material={materials['Material.557']} />
        <mesh geometry={nodes.Cube032_75.geometry} material={materials['Material.554']} />
        <mesh geometry={nodes.Cube032_76.geometry} material={materials['Material.551']} />
        <mesh geometry={nodes.Cube032_77.geometry} material={materials['Material.552']} />
        <mesh geometry={nodes.Cube032_78.geometry} material={materials['Material.550']} />
        <mesh geometry={nodes.Cube032_79.geometry} material={materials['Material.553']} />
        <mesh geometry={nodes.Cube032_80.geometry} material={materials['Material.572']} />
        <mesh geometry={nodes.Cube032_81.geometry} material={materials['Material.571']} />
        <mesh geometry={nodes.Cube032_82.geometry} material={materials['Material.573']} />
        <mesh geometry={nodes.Cube032_83.geometry} material={materials['Material.570']} />
        <mesh geometry={nodes.Cube032_84.geometry} material={materials['Material.567']} />
        <mesh geometry={nodes.Cube032_85.geometry} material={materials['Material.568']} />
        <mesh geometry={nodes.Cube032_86.geometry} material={materials['Material.566']} />
        <mesh geometry={nodes.Cube032_87.geometry} material={materials['Material.569']} />
        <mesh geometry={nodes.Cube032_88.geometry} material={materials['Material.559']} />
        <mesh geometry={nodes.Cube032_89.geometry} material={materials['Material.560']} />
        <mesh geometry={nodes.Cube032_90.geometry} material={materials['Material.558']} />
        <mesh geometry={nodes.Cube032_91.geometry} material={materials['Material.561']} />
        <mesh geometry={nodes.Cube032_92.geometry} material={materials['Material.564']} />
        <mesh geometry={nodes.Cube032_93.geometry} material={materials['Material.563']} />
        <mesh geometry={nodes.Cube032_94.geometry} material={materials['Material.565']} />
        <mesh geometry={nodes.Cube032_95.geometry} material={materials['Material.562']} />
        <mesh geometry={nodes.Cube032_96.geometry} material={materials['Material.508']} />
        <mesh geometry={nodes.Cube032_97.geometry} material={materials['Material.507']} />
        <mesh geometry={nodes.Cube032_98.geometry} material={materials['Material.509']} />
        <mesh geometry={nodes.Cube032_99.geometry} material={materials['Material.506']} />
        <mesh geometry={nodes.Cube032_100.geometry} material={materials['Material.503']} />
        <mesh geometry={nodes.Cube032_101.geometry} material={materials['Material.504']} />
        <mesh geometry={nodes.Cube032_102.geometry} material={materials['Material.502']} />
        <mesh geometry={nodes.Cube032_103.geometry} material={materials['Material.505']} />
        <mesh geometry={nodes.Cube032_104.geometry} material={materials['Material.495']} />
        <mesh geometry={nodes.Cube032_105.geometry} material={materials['Material.496']} />
        <mesh geometry={nodes.Cube032_106.geometry} material={materials['Material.494']} />
        <mesh geometry={nodes.Cube032_107.geometry} material={materials['Material.497']} />
        <mesh geometry={nodes.Cube032_108.geometry} material={materials['Material.500']} />
        <mesh geometry={nodes.Cube032_109.geometry} material={materials['Material.499']} />
        <mesh geometry={nodes.Cube032_110.geometry} material={materials['Material.501']} />
        <mesh geometry={nodes.Cube032_111.geometry} material={materials['Material.498']} />
        <mesh geometry={nodes.Cube032_112.geometry} material={materials['Material.479']} />
        <mesh geometry={nodes.Cube032_113.geometry} material={materials['Material.480']} />
        <mesh geometry={nodes.Cube032_114.geometry} material={materials['Material.478']} />
        <mesh geometry={nodes.Cube032_115.geometry} material={materials['Material.481']} />
        <mesh geometry={nodes.Cube032_116.geometry} material={materials['Material.484']} />
        <mesh geometry={nodes.Cube032_117.geometry} material={materials['Material.483']} />
        <mesh geometry={nodes.Cube032_118.geometry} material={materials['Material.485']} />
        <mesh geometry={nodes.Cube032_119.geometry} material={materials['Material.482']} />
        <mesh geometry={nodes.Cube032_120.geometry} material={materials['Material.492']} />
        <mesh geometry={nodes.Cube032_121.geometry} material={materials['Material.491']} />
        <mesh geometry={nodes.Cube032_122.geometry} material={materials['Material.493']} />
        <mesh geometry={nodes.Cube032_123.geometry} material={materials['Material.490']} />
        <mesh geometry={nodes.Cube032_124.geometry} material={materials['Material.487']} />
        <mesh geometry={nodes.Cube032_125.geometry} material={materials['Material.488']} />
        <mesh geometry={nodes.Cube032_126.geometry} material={materials['Material.486']} />
        <mesh geometry={nodes.Cube032_127.geometry} material={materials['Material.489']} />
        <mesh geometry={nodes.Cube032_128.geometry} material={materials['Material.415']} />
        <mesh geometry={nodes.Cube032_129.geometry} material={materials['Material.416']} />
        <mesh geometry={nodes.Cube032_130.geometry} material={materials['Material.414']} />
        <mesh geometry={nodes.Cube032_131.geometry} material={materials['Material.417']} />
        <mesh geometry={nodes.Cube032_132.geometry} material={materials['Material.420']} />
        <mesh geometry={nodes.Cube032_133.geometry} material={materials['Material.419']} />
        <mesh geometry={nodes.Cube032_134.geometry} material={materials['Material.421']} />
        <mesh geometry={nodes.Cube032_135.geometry} material={materials['Material.418']} />
        <mesh geometry={nodes.Cube032_136.geometry} material={materials['Material.428']} />
        <mesh geometry={nodes.Cube032_137.geometry} material={materials['Material.427']} />
        <mesh geometry={nodes.Cube032_138.geometry} material={materials['Material.429']} />
        <mesh geometry={nodes.Cube032_139.geometry} material={materials['Material.426']} />
        <mesh geometry={nodes.Cube032_140.geometry} material={materials['Material.423']} />
        <mesh geometry={nodes.Cube032_141.geometry} material={materials['Material.424']} />
        <mesh geometry={nodes.Cube032_142.geometry} material={materials['Material.422']} />
        <mesh geometry={nodes.Cube032_143.geometry} material={materials['Material.425']} />
        <mesh geometry={nodes.Cube032_144.geometry} material={materials['Material.444']} />
        <mesh geometry={nodes.Cube032_145.geometry} material={materials['Material.443']} />
        <mesh geometry={nodes.Cube032_146.geometry} material={materials['Material.445']} />
        <mesh geometry={nodes.Cube032_147.geometry} material={materials['Material.442']} />
        <mesh geometry={nodes.Cube032_148.geometry} material={materials['Material.439']} />
        <mesh geometry={nodes.Cube032_149.geometry} material={materials['Material.440']} />
        <mesh geometry={nodes.Cube032_150.geometry} material={materials['Material.438']} />
        <mesh geometry={nodes.Cube032_151.geometry} material={materials['Material.441']} />
        <mesh geometry={nodes.Cube032_152.geometry} material={materials['Material.431']} />
        <mesh geometry={nodes.Cube032_153.geometry} material={materials['Material.432']} />
        <mesh geometry={nodes.Cube032_154.geometry} material={materials['Material.430']} />
        <mesh geometry={nodes.Cube032_155.geometry} material={materials['Material.433']} />
        <mesh geometry={nodes.Cube032_156.geometry} material={materials['Material.436']} />
        <mesh geometry={nodes.Cube032_157.geometry} material={materials['Material.435']} />
        <mesh geometry={nodes.Cube032_158.geometry} material={materials['Material.437']} />
        <mesh geometry={nodes.Cube032_159.geometry} material={materials['Material.434']} />
        <mesh geometry={nodes.Cube032_160.geometry} material={materials['Material.476']} />
        <mesh geometry={nodes.Cube032_161.geometry} material={materials['Material.475']} />
        <mesh geometry={nodes.Cube032_162.geometry} material={materials['Material.477']} />
        <mesh geometry={nodes.Cube032_163.geometry} material={materials['Material.474']} />
        <mesh geometry={nodes.Cube032_164.geometry} material={materials['Material.471']} />
        <mesh geometry={nodes.Cube032_165.geometry} material={materials['Material.472']} />
        <mesh geometry={nodes.Cube032_166.geometry} material={materials['Material.470']} />
        <mesh geometry={nodes.Cube032_167.geometry} material={materials['Material.473']} />
        <mesh geometry={nodes.Cube032_168.geometry} material={materials['Material.463']} />
        <mesh geometry={nodes.Cube032_169.geometry} material={materials['Material.464']} />
        <mesh geometry={nodes.Cube032_170.geometry} material={materials['Material.462']} />
        <mesh geometry={nodes.Cube032_171.geometry} material={materials['Material.465']} />
        <mesh geometry={nodes.Cube032_172.geometry} material={materials['Material.468']} />
        <mesh geometry={nodes.Cube032_173.geometry} material={materials['Material.467']} />
        <mesh geometry={nodes.Cube032_174.geometry} material={materials['Material.469']} />
        <mesh geometry={nodes.Cube032_175.geometry} material={materials['Material.466']} />
        <mesh geometry={nodes.Cube032_176.geometry} material={materials['Material.447']} />
        <mesh geometry={nodes.Cube032_177.geometry} material={materials['Material.448']} />
        <mesh geometry={nodes.Cube032_178.geometry} material={materials['Material.446']} />
        <mesh geometry={nodes.Cube032_179.geometry} material={materials['Material.449']} />
        <mesh geometry={nodes.Cube032_180.geometry} material={materials['Material.452']} />
        <mesh geometry={nodes.Cube032_181.geometry} material={materials['Material.451']} />
        <mesh geometry={nodes.Cube032_182.geometry} material={materials['Material.453']} />
        <mesh geometry={nodes.Cube032_183.geometry} material={materials['Material.450']} />
        <mesh geometry={nodes.Cube032_184.geometry} material={materials['Material.460']} />
        <mesh geometry={nodes.Cube032_185.geometry} material={materials['Material.459']} />
        <mesh geometry={nodes.Cube032_186.geometry} material={materials['Material.461']} />
        <mesh geometry={nodes.Cube032_187.geometry} material={materials['Material.458']} />
        <mesh geometry={nodes.Cube032_188.geometry} material={materials['Material.455']} />
        <mesh geometry={nodes.Cube032_189.geometry} material={materials['Material.456']} />
        <mesh geometry={nodes.Cube032_190.geometry} material={materials['Material.454']} />
        <mesh geometry={nodes.Cube032_191.geometry} material={materials['Material.457']} />
      </group>
      <group position={[-4.24, 1.62, 9.77]} rotation={[0.26, 1.38, 0.12]} scale={[0.11, 0.11, 0.03]}>
        <mesh geometry={nodes.Cube033.geometry} material={materials['Material.703']} />
        <mesh geometry={nodes.Cube033_1.geometry} material={materials['Material.704']} />
        <mesh geometry={nodes.Cube033_2.geometry} material={materials['Material.702']} />
        <mesh geometry={nodes.Cube033_3.geometry} material={materials['Material.705']} />
        <mesh geometry={nodes.Cube033_4.geometry} material={materials['Material.708']} />
        <mesh geometry={nodes.Cube033_5.geometry} material={materials['Material.707']} />
        <mesh geometry={nodes.Cube033_6.geometry} material={materials['Material.709']} />
        <mesh geometry={nodes.Cube033_7.geometry} material={materials['Material.706']} />
        <mesh geometry={nodes.Cube033_8.geometry} material={materials['Material.716']} />
        <mesh geometry={nodes.Cube033_9.geometry} material={materials['Material.715']} />
        <mesh geometry={nodes.Cube033_10.geometry} material={materials['Material.717']} />
        <mesh geometry={nodes.Cube033_11.geometry} material={materials['Material.714']} />
        <mesh geometry={nodes.Cube033_12.geometry} material={materials['Material.711']} />
        <mesh geometry={nodes.Cube033_13.geometry} material={materials['Material.712']} />
        <mesh geometry={nodes.Cube033_14.geometry} material={materials['Material.710']} />
        <mesh geometry={nodes.Cube033_15.geometry} material={materials['Material.713']} />
        <mesh geometry={nodes.Cube033_16.geometry} material={materials['Material.732']} />
        <mesh geometry={nodes.Cube033_17.geometry} material={materials['Material.731']} />
        <mesh geometry={nodes.Cube033_18.geometry} material={materials['Material.733']} />
        <mesh geometry={nodes.Cube033_19.geometry} material={materials['Material.730']} />
        <mesh geometry={nodes.Cube033_20.geometry} material={materials['Material.727']} />
        <mesh geometry={nodes.Cube033_21.geometry} material={materials['Material.728']} />
        <mesh geometry={nodes.Cube033_22.geometry} material={materials['Material.726']} />
        <mesh geometry={nodes.Cube033_23.geometry} material={materials['Material.729']} />
        <mesh geometry={nodes.Cube033_24.geometry} material={materials['Material.719']} />
        <mesh geometry={nodes.Cube033_25.geometry} material={materials['Material.720']} />
        <mesh geometry={nodes.Cube033_26.geometry} material={materials['Material.718']} />
        <mesh geometry={nodes.Cube033_27.geometry} material={materials['Material.721']} />
        <mesh geometry={nodes.Cube033_28.geometry} material={materials['Material.724']} />
        <mesh geometry={nodes.Cube033_29.geometry} material={materials['Material.723']} />
        <mesh geometry={nodes.Cube033_30.geometry} material={materials['Material.725']} />
        <mesh geometry={nodes.Cube033_31.geometry} material={materials['Material.722']} />
        <mesh geometry={nodes.Cube033_32.geometry} material={materials['Material.796']} />
        <mesh geometry={nodes.Cube033_33.geometry} material={materials['Material.795']} />
        <mesh geometry={nodes.Cube033_34.geometry} material={materials['Material.797']} />
        <mesh geometry={nodes.Cube033_35.geometry} material={materials['Material.794']} />
        <mesh geometry={nodes.Cube033_36.geometry} material={materials['Material.791']} />
        <mesh geometry={nodes.Cube033_37.geometry} material={materials['Material.792']} />
        <mesh geometry={nodes.Cube033_38.geometry} material={materials['Material.790']} />
        <mesh geometry={nodes.Cube033_39.geometry} material={materials['Material.793']} />
        <mesh geometry={nodes.Cube033_40.geometry} material={materials['Material.783']} />
        <mesh geometry={nodes.Cube033_41.geometry} material={materials['Material.784']} />
        <mesh geometry={nodes.Cube033_42.geometry} material={materials['Material.782']} />
        <mesh geometry={nodes.Cube033_43.geometry} material={materials['Material.785']} />
        <mesh geometry={nodes.Cube033_44.geometry} material={materials['Material.788']} />
        <mesh geometry={nodes.Cube033_45.geometry} material={materials['Material.787']} />
        <mesh geometry={nodes.Cube033_46.geometry} material={materials['Material.789']} />
        <mesh geometry={nodes.Cube033_47.geometry} material={materials['Material.786']} />
        <mesh geometry={nodes.Cube033_48.geometry} material={materials['Material.767']} />
        <mesh geometry={nodes.Cube033_49.geometry} material={materials['Material.768']} />
        <mesh geometry={nodes.Cube033_50.geometry} material={materials['Material.766']} />
        <mesh geometry={nodes.Cube033_51.geometry} material={materials['Material.769']} />
        <mesh geometry={nodes.Cube033_52.geometry} material={materials['Material.772']} />
        <mesh geometry={nodes.Cube033_53.geometry} material={materials['Material.771']} />
        <mesh geometry={nodes.Cube033_54.geometry} material={materials['Material.773']} />
        <mesh geometry={nodes.Cube033_55.geometry} material={materials['Material.770']} />
        <mesh geometry={nodes.Cube033_56.geometry} material={materials['Material.780']} />
        <mesh geometry={nodes.Cube033_57.geometry} material={materials['Material.779']} />
        <mesh geometry={nodes.Cube033_58.geometry} material={materials['Material.781']} />
        <mesh geometry={nodes.Cube033_59.geometry} material={materials['Material.778']} />
        <mesh geometry={nodes.Cube033_60.geometry} material={materials['Material.775']} />
        <mesh geometry={nodes.Cube033_61.geometry} material={materials['Material.776']} />
        <mesh geometry={nodes.Cube033_62.geometry} material={materials['Material.774']} />
        <mesh geometry={nodes.Cube033_63.geometry} material={materials['Material.777']} />
        <mesh geometry={nodes.Cube033_64.geometry} material={materials['Material.735']} />
        <mesh geometry={nodes.Cube033_65.geometry} material={materials['Material.736']} />
        <mesh geometry={nodes.Cube033_66.geometry} material={materials['Material.734']} />
        <mesh geometry={nodes.Cube033_67.geometry} material={materials['Material.737']} />
        <mesh geometry={nodes.Cube033_68.geometry} material={materials['Material.740']} />
        <mesh geometry={nodes.Cube033_69.geometry} material={materials['Material.739']} />
        <mesh geometry={nodes.Cube033_70.geometry} material={materials['Material.741']} />
        <mesh geometry={nodes.Cube033_71.geometry} material={materials['Material.738']} />
        <mesh geometry={nodes.Cube033_72.geometry} material={materials['Material.748']} />
        <mesh geometry={nodes.Cube033_73.geometry} material={materials['Material.747']} />
        <mesh geometry={nodes.Cube033_74.geometry} material={materials['Material.749']} />
        <mesh geometry={nodes.Cube033_75.geometry} material={materials['Material.746']} />
        <mesh geometry={nodes.Cube033_76.geometry} material={materials['Material.743']} />
        <mesh geometry={nodes.Cube033_77.geometry} material={materials['Material.744']} />
        <mesh geometry={nodes.Cube033_78.geometry} material={materials['Material.742']} />
        <mesh geometry={nodes.Cube033_79.geometry} material={materials['Material.745']} />
        <mesh geometry={nodes.Cube033_80.geometry} material={materials['Material.764']} />
        <mesh geometry={nodes.Cube033_81.geometry} material={materials['Material.763']} />
        <mesh geometry={nodes.Cube033_82.geometry} material={materials['Material.765']} />
        <mesh geometry={nodes.Cube033_83.geometry} material={materials['Material.762']} />
        <mesh geometry={nodes.Cube033_84.geometry} material={materials['Material.759']} />
        <mesh geometry={nodes.Cube033_85.geometry} material={materials['Material.760']} />
        <mesh geometry={nodes.Cube033_86.geometry} material={materials['Material.758']} />
        <mesh geometry={nodes.Cube033_87.geometry} material={materials['Material.761']} />
        <mesh geometry={nodes.Cube033_88.geometry} material={materials['Material.751']} />
        <mesh geometry={nodes.Cube033_89.geometry} material={materials['Material.752']} />
        <mesh geometry={nodes.Cube033_90.geometry} material={materials['Material.750']} />
        <mesh geometry={nodes.Cube033_91.geometry} material={materials['Material.753']} />
        <mesh geometry={nodes.Cube033_92.geometry} material={materials['Material.756']} />
        <mesh geometry={nodes.Cube033_93.geometry} material={materials['Material.755']} />
        <mesh geometry={nodes.Cube033_94.geometry} material={materials['Material.757']} />
        <mesh geometry={nodes.Cube033_95.geometry} material={materials['Material.754']} />
        <mesh geometry={nodes.Cube033_96.geometry} material={materials['Material.700']} />
        <mesh geometry={nodes.Cube033_97.geometry} material={materials['Material.699']} />
        <mesh geometry={nodes.Cube033_98.geometry} material={materials['Material.701']} />
        <mesh geometry={nodes.Cube033_99.geometry} material={materials['Material.698']} />
        <mesh geometry={nodes.Cube033_100.geometry} material={materials['Material.695']} />
        <mesh geometry={nodes.Cube033_101.geometry} material={materials['Material.696']} />
        <mesh geometry={nodes.Cube033_102.geometry} material={materials['Material.694']} />
        <mesh geometry={nodes.Cube033_103.geometry} material={materials['Material.697']} />
        <mesh geometry={nodes.Cube033_104.geometry} material={materials['Material.687']} />
        <mesh geometry={nodes.Cube033_105.geometry} material={materials['Material.688']} />
        <mesh geometry={nodes.Cube033_106.geometry} material={materials['Material.686']} />
        <mesh geometry={nodes.Cube033_107.geometry} material={materials['Material.689']} />
        <mesh geometry={nodes.Cube033_108.geometry} material={materials['Material.692']} />
        <mesh geometry={nodes.Cube033_109.geometry} material={materials['Material.691']} />
        <mesh geometry={nodes.Cube033_110.geometry} material={materials['Material.693']} />
        <mesh geometry={nodes.Cube033_111.geometry} material={materials['Material.690']} />
        <mesh geometry={nodes.Cube033_112.geometry} material={materials['Material.671']} />
        <mesh geometry={nodes.Cube033_113.geometry} material={materials['Material.672']} />
        <mesh geometry={nodes.Cube033_114.geometry} material={materials['Material.670']} />
        <mesh geometry={nodes.Cube033_115.geometry} material={materials['Material.673']} />
        <mesh geometry={nodes.Cube033_116.geometry} material={materials['Material.676']} />
        <mesh geometry={nodes.Cube033_117.geometry} material={materials['Material.675']} />
        <mesh geometry={nodes.Cube033_118.geometry} material={materials['Material.677']} />
        <mesh geometry={nodes.Cube033_119.geometry} material={materials['Material.674']} />
        <mesh geometry={nodes.Cube033_120.geometry} material={materials['Material.684']} />
        <mesh geometry={nodes.Cube033_121.geometry} material={materials['Material.683']} />
        <mesh geometry={nodes.Cube033_122.geometry} material={materials['Material.685']} />
        <mesh geometry={nodes.Cube033_123.geometry} material={materials['Material.682']} />
        <mesh geometry={nodes.Cube033_124.geometry} material={materials['Material.679']} />
        <mesh geometry={nodes.Cube033_125.geometry} material={materials['Material.680']} />
        <mesh geometry={nodes.Cube033_126.geometry} material={materials['Material.678']} />
        <mesh geometry={nodes.Cube033_127.geometry} material={materials['Material.681']} />
        <mesh geometry={nodes.Cube033_128.geometry} material={materials['Material.607']} />
        <mesh geometry={nodes.Cube033_129.geometry} material={materials['Material.608']} />
        <mesh geometry={nodes.Cube033_130.geometry} material={materials['Material.606']} />
        <mesh geometry={nodes.Cube033_131.geometry} material={materials['Material.609']} />
        <mesh geometry={nodes.Cube033_132.geometry} material={materials['Material.612']} />
        <mesh geometry={nodes.Cube033_133.geometry} material={materials['Material.611']} />
        <mesh geometry={nodes.Cube033_134.geometry} material={materials['Material.613']} />
        <mesh geometry={nodes.Cube033_135.geometry} material={materials['Material.610']} />
        <mesh geometry={nodes.Cube033_136.geometry} material={materials['Material.620']} />
        <mesh geometry={nodes.Cube033_137.geometry} material={materials['Material.619']} />
        <mesh geometry={nodes.Cube033_138.geometry} material={materials['Material.621']} />
        <mesh geometry={nodes.Cube033_139.geometry} material={materials['Material.618']} />
        <mesh geometry={nodes.Cube033_140.geometry} material={materials['Material.615']} />
        <mesh geometry={nodes.Cube033_141.geometry} material={materials['Material.616']} />
        <mesh geometry={nodes.Cube033_142.geometry} material={materials['Material.614']} />
        <mesh geometry={nodes.Cube033_143.geometry} material={materials['Material.617']} />
        <mesh geometry={nodes.Cube033_144.geometry} material={materials['Material.636']} />
        <mesh geometry={nodes.Cube033_145.geometry} material={materials['Material.635']} />
        <mesh geometry={nodes.Cube033_146.geometry} material={materials['Material.637']} />
        <mesh geometry={nodes.Cube033_147.geometry} material={materials['Material.634']} />
        <mesh geometry={nodes.Cube033_148.geometry} material={materials['Material.631']} />
        <mesh geometry={nodes.Cube033_149.geometry} material={materials['Material.632']} />
        <mesh geometry={nodes.Cube033_150.geometry} material={materials['Material.630']} />
        <mesh geometry={nodes.Cube033_151.geometry} material={materials['Material.633']} />
        <mesh geometry={nodes.Cube033_152.geometry} material={materials['Material.623']} />
        <mesh geometry={nodes.Cube033_153.geometry} material={materials['Material.624']} />
        <mesh geometry={nodes.Cube033_154.geometry} material={materials['Material.622']} />
        <mesh geometry={nodes.Cube033_155.geometry} material={materials['Material.625']} />
        <mesh geometry={nodes.Cube033_156.geometry} material={materials['Material.628']} />
        <mesh geometry={nodes.Cube033_157.geometry} material={materials['Material.627']} />
        <mesh geometry={nodes.Cube033_158.geometry} material={materials['Material.629']} />
        <mesh geometry={nodes.Cube033_159.geometry} material={materials['Material.626']} />
        <mesh geometry={nodes.Cube033_160.geometry} material={materials['Material.668']} />
        <mesh geometry={nodes.Cube033_161.geometry} material={materials['Material.667']} />
        <mesh geometry={nodes.Cube033_162.geometry} material={materials['Material.669']} />
        <mesh geometry={nodes.Cube033_163.geometry} material={materials['Material.666']} />
        <mesh geometry={nodes.Cube033_164.geometry} material={materials['Material.663']} />
        <mesh geometry={nodes.Cube033_165.geometry} material={materials['Material.664']} />
        <mesh geometry={nodes.Cube033_166.geometry} material={materials['Material.662']} />
        <mesh geometry={nodes.Cube033_167.geometry} material={materials['Material.665']} />
        <mesh geometry={nodes.Cube033_168.geometry} material={materials['Material.655']} />
        <mesh geometry={nodes.Cube033_169.geometry} material={materials['Material.656']} />
        <mesh geometry={nodes.Cube033_170.geometry} material={materials['Material.654']} />
        <mesh geometry={nodes.Cube033_171.geometry} material={materials['Material.657']} />
        <mesh geometry={nodes.Cube033_172.geometry} material={materials['Material.660']} />
        <mesh geometry={nodes.Cube033_173.geometry} material={materials['Material.659']} />
        <mesh geometry={nodes.Cube033_174.geometry} material={materials['Material.661']} />
        <mesh geometry={nodes.Cube033_175.geometry} material={materials['Material.658']} />
        <mesh geometry={nodes.Cube033_176.geometry} material={materials['Material.639']} />
        <mesh geometry={nodes.Cube033_177.geometry} material={materials['Material.640']} />
        <mesh geometry={nodes.Cube033_178.geometry} material={materials['Material.638']} />
        <mesh geometry={nodes.Cube033_179.geometry} material={materials['Material.641']} />
        <mesh geometry={nodes.Cube033_180.geometry} material={materials['Material.644']} />
        <mesh geometry={nodes.Cube033_181.geometry} material={materials['Material.643']} />
        <mesh geometry={nodes.Cube033_182.geometry} material={materials['Material.645']} />
        <mesh geometry={nodes.Cube033_183.geometry} material={materials['Material.642']} />
        <mesh geometry={nodes.Cube033_184.geometry} material={materials['Material.652']} />
        <mesh geometry={nodes.Cube033_185.geometry} material={materials['Material.651']} />
        <mesh geometry={nodes.Cube033_186.geometry} material={materials['Material.653']} />
        <mesh geometry={nodes.Cube033_187.geometry} material={materials['Material.650']} />
        <mesh geometry={nodes.Cube033_188.geometry} material={materials['Material.647']} />
        <mesh geometry={nodes.Cube033_189.geometry} material={materials['Material.648']} />
        <mesh geometry={nodes.Cube033_190.geometry} material={materials['Material.646']} />
        <mesh geometry={nodes.Cube033_191.geometry} material={materials['Material.649']} />
      </group>
      <group position={[2.62, 2.23, -20.09]} rotation={[0.33, 1.31, -0.37]} scale={[0.11, 0.11, 0.03]}>
        <mesh geometry={nodes.Cube034.geometry} material={materials['Material.895']} />
        <mesh geometry={nodes.Cube034_1.geometry} material={materials['Material.896']} />
        <mesh geometry={nodes.Cube034_2.geometry} material={materials['Material.894']} />
        <mesh geometry={nodes.Cube034_3.geometry} material={materials['Material.897']} />
        <mesh geometry={nodes.Cube034_4.geometry} material={materials['Material.900']} />
        <mesh geometry={nodes.Cube034_5.geometry} material={materials['Material.899']} />
        <mesh geometry={nodes.Cube034_6.geometry} material={materials['Material.901']} />
        <mesh geometry={nodes.Cube034_7.geometry} material={materials['Material.898']} />
        <mesh geometry={nodes.Cube034_8.geometry} material={materials['Material.908']} />
        <mesh geometry={nodes.Cube034_9.geometry} material={materials['Material.907']} />
        <mesh geometry={nodes.Cube034_10.geometry} material={materials['Material.909']} />
        <mesh geometry={nodes.Cube034_11.geometry} material={materials['Material.906']} />
        <mesh geometry={nodes.Cube034_12.geometry} material={materials['Material.903']} />
        <mesh geometry={nodes.Cube034_13.geometry} material={materials['Material.904']} />
        <mesh geometry={nodes.Cube034_14.geometry} material={materials['Material.902']} />
        <mesh geometry={nodes.Cube034_15.geometry} material={materials['Material.905']} />
        <mesh geometry={nodes.Cube034_16.geometry} material={materials['Material.924']} />
        <mesh geometry={nodes.Cube034_17.geometry} material={materials['Material.923']} />
        <mesh geometry={nodes.Cube034_18.geometry} material={materials['Material.925']} />
        <mesh geometry={nodes.Cube034_19.geometry} material={materials['Material.922']} />
        <mesh geometry={nodes.Cube034_20.geometry} material={materials['Material.919']} />
        <mesh geometry={nodes.Cube034_21.geometry} material={materials['Material.920']} />
        <mesh geometry={nodes.Cube034_22.geometry} material={materials['Material.918']} />
        <mesh geometry={nodes.Cube034_23.geometry} material={materials['Material.921']} />
        <mesh geometry={nodes.Cube034_24.geometry} material={materials['Material.911']} />
        <mesh geometry={nodes.Cube034_25.geometry} material={materials['Material.912']} />
        <mesh geometry={nodes.Cube034_26.geometry} material={materials['Material.910']} />
        <mesh geometry={nodes.Cube034_27.geometry} material={materials['Material.913']} />
        <mesh geometry={nodes.Cube034_28.geometry} material={materials['Material.916']} />
        <mesh geometry={nodes.Cube034_29.geometry} material={materials['Material.915']} />
        <mesh geometry={nodes.Cube034_30.geometry} material={materials['Material.917']} />
        <mesh geometry={nodes.Cube034_31.geometry} material={materials['Material.914']} />
        <mesh geometry={nodes.Cube034_32.geometry} material={materials['Material.988']} />
        <mesh geometry={nodes.Cube034_33.geometry} material={materials['Material.987']} />
        <mesh geometry={nodes.Cube034_34.geometry} material={materials['Material.989']} />
        <mesh geometry={nodes.Cube034_35.geometry} material={materials['Material.986']} />
        <mesh geometry={nodes.Cube034_36.geometry} material={materials['Material.983']} />
        <mesh geometry={nodes.Cube034_37.geometry} material={materials['Material.984']} />
        <mesh geometry={nodes.Cube034_38.geometry} material={materials['Material.982']} />
        <mesh geometry={nodes.Cube034_39.geometry} material={materials['Material.985']} />
        <mesh geometry={nodes.Cube034_40.geometry} material={materials['Material.975']} />
        <mesh geometry={nodes.Cube034_41.geometry} material={materials['Material.976']} />
        <mesh geometry={nodes.Cube034_42.geometry} material={materials['Material.974']} />
        <mesh geometry={nodes.Cube034_43.geometry} material={materials['Material.977']} />
        <mesh geometry={nodes.Cube034_44.geometry} material={materials['Material.980']} />
        <mesh geometry={nodes.Cube034_45.geometry} material={materials['Material.979']} />
        <mesh geometry={nodes.Cube034_46.geometry} material={materials['Material.981']} />
        <mesh geometry={nodes.Cube034_47.geometry} material={materials['Material.978']} />
        <mesh geometry={nodes.Cube034_48.geometry} material={materials['Material.959']} />
        <mesh geometry={nodes.Cube034_49.geometry} material={materials['Material.960']} />
        <mesh geometry={nodes.Cube034_50.geometry} material={materials['Material.958']} />
        <mesh geometry={nodes.Cube034_51.geometry} material={materials['Material.961']} />
        <mesh geometry={nodes.Cube034_52.geometry} material={materials['Material.964']} />
        <mesh geometry={nodes.Cube034_53.geometry} material={materials['Material.963']} />
        <mesh geometry={nodes.Cube034_54.geometry} material={materials['Material.965']} />
        <mesh geometry={nodes.Cube034_55.geometry} material={materials['Material.962']} />
        <mesh geometry={nodes.Cube034_56.geometry} material={materials['Material.972']} />
        <mesh geometry={nodes.Cube034_57.geometry} material={materials['Material.971']} />
        <mesh geometry={nodes.Cube034_58.geometry} material={materials['Material.973']} />
        <mesh geometry={nodes.Cube034_59.geometry} material={materials['Material.970']} />
        <mesh geometry={nodes.Cube034_60.geometry} material={materials['Material.967']} />
        <mesh geometry={nodes.Cube034_61.geometry} material={materials['Material.968']} />
        <mesh geometry={nodes.Cube034_62.geometry} material={materials['Material.966']} />
        <mesh geometry={nodes.Cube034_63.geometry} material={materials['Material.969']} />
        <mesh geometry={nodes.Cube034_64.geometry} material={materials['Material.927']} />
        <mesh geometry={nodes.Cube034_65.geometry} material={materials['Material.928']} />
        <mesh geometry={nodes.Cube034_66.geometry} material={materials['Material.926']} />
        <mesh geometry={nodes.Cube034_67.geometry} material={materials['Material.929']} />
        <mesh geometry={nodes.Cube034_68.geometry} material={materials['Material.932']} />
        <mesh geometry={nodes.Cube034_69.geometry} material={materials['Material.931']} />
        <mesh geometry={nodes.Cube034_70.geometry} material={materials['Material.933']} />
        <mesh geometry={nodes.Cube034_71.geometry} material={materials['Material.930']} />
        <mesh geometry={nodes.Cube034_72.geometry} material={materials['Material.940']} />
        <mesh geometry={nodes.Cube034_73.geometry} material={materials['Material.939']} />
        <mesh geometry={nodes.Cube034_74.geometry} material={materials['Material.941']} />
        <mesh geometry={nodes.Cube034_75.geometry} material={materials['Material.938']} />
        <mesh geometry={nodes.Cube034_76.geometry} material={materials['Material.935']} />
        <mesh geometry={nodes.Cube034_77.geometry} material={materials['Material.936']} />
        <mesh geometry={nodes.Cube034_78.geometry} material={materials['Material.934']} />
        <mesh geometry={nodes.Cube034_79.geometry} material={materials['Material.937']} />
        <mesh geometry={nodes.Cube034_80.geometry} material={materials['Material.956']} />
        <mesh geometry={nodes.Cube034_81.geometry} material={materials['Material.955']} />
        <mesh geometry={nodes.Cube034_82.geometry} material={materials['Material.957']} />
        <mesh geometry={nodes.Cube034_83.geometry} material={materials['Material.954']} />
        <mesh geometry={nodes.Cube034_84.geometry} material={materials['Material.951']} />
        <mesh geometry={nodes.Cube034_85.geometry} material={materials['Material.952']} />
        <mesh geometry={nodes.Cube034_86.geometry} material={materials['Material.950']} />
        <mesh geometry={nodes.Cube034_87.geometry} material={materials['Material.953']} />
        <mesh geometry={nodes.Cube034_88.geometry} material={materials['Material.943']} />
        <mesh geometry={nodes.Cube034_89.geometry} material={materials['Material.944']} />
        <mesh geometry={nodes.Cube034_90.geometry} material={materials['Material.942']} />
        <mesh geometry={nodes.Cube034_91.geometry} material={materials['Material.945']} />
        <mesh geometry={nodes.Cube034_92.geometry} material={materials['Material.948']} />
        <mesh geometry={nodes.Cube034_93.geometry} material={materials['Material.947']} />
        <mesh geometry={nodes.Cube034_94.geometry} material={materials['Material.949']} />
        <mesh geometry={nodes.Cube034_95.geometry} material={materials['Material.946']} />
        <mesh geometry={nodes.Cube034_96.geometry} material={materials['Material.892']} />
        <mesh geometry={nodes.Cube034_97.geometry} material={materials['Material.891']} />
        <mesh geometry={nodes.Cube034_98.geometry} material={materials['Material.893']} />
        <mesh geometry={nodes.Cube034_99.geometry} material={materials['Material.890']} />
        <mesh geometry={nodes.Cube034_100.geometry} material={materials['Material.887']} />
        <mesh geometry={nodes.Cube034_101.geometry} material={materials['Material.888']} />
        <mesh geometry={nodes.Cube034_102.geometry} material={materials['Material.886']} />
        <mesh geometry={nodes.Cube034_103.geometry} material={materials['Material.889']} />
        <mesh geometry={nodes.Cube034_104.geometry} material={materials['Material.879']} />
        <mesh geometry={nodes.Cube034_105.geometry} material={materials['Material.880']} />
        <mesh geometry={nodes.Cube034_106.geometry} material={materials['Material.878']} />
        <mesh geometry={nodes.Cube034_107.geometry} material={materials['Material.881']} />
        <mesh geometry={nodes.Cube034_108.geometry} material={materials['Material.884']} />
        <mesh geometry={nodes.Cube034_109.geometry} material={materials['Material.883']} />
        <mesh geometry={nodes.Cube034_110.geometry} material={materials['Material.885']} />
        <mesh geometry={nodes.Cube034_111.geometry} material={materials['Material.882']} />
        <mesh geometry={nodes.Cube034_112.geometry} material={materials['Material.863']} />
        <mesh geometry={nodes.Cube034_113.geometry} material={materials['Material.864']} />
        <mesh geometry={nodes.Cube034_114.geometry} material={materials['Material.862']} />
        <mesh geometry={nodes.Cube034_115.geometry} material={materials['Material.865']} />
        <mesh geometry={nodes.Cube034_116.geometry} material={materials['Material.868']} />
        <mesh geometry={nodes.Cube034_117.geometry} material={materials['Material.867']} />
        <mesh geometry={nodes.Cube034_118.geometry} material={materials['Material.869']} />
        <mesh geometry={nodes.Cube034_119.geometry} material={materials['Material.866']} />
        <mesh geometry={nodes.Cube034_120.geometry} material={materials['Material.876']} />
        <mesh geometry={nodes.Cube034_121.geometry} material={materials['Material.875']} />
        <mesh geometry={nodes.Cube034_122.geometry} material={materials['Material.877']} />
        <mesh geometry={nodes.Cube034_123.geometry} material={materials['Material.874']} />
        <mesh geometry={nodes.Cube034_124.geometry} material={materials['Material.871']} />
        <mesh geometry={nodes.Cube034_125.geometry} material={materials['Material.872']} />
        <mesh geometry={nodes.Cube034_126.geometry} material={materials['Material.870']} />
        <mesh geometry={nodes.Cube034_127.geometry} material={materials['Material.873']} />
        <mesh geometry={nodes.Cube034_128.geometry} material={materials['Material.799']} />
        <mesh geometry={nodes.Cube034_129.geometry} material={materials['Material.800']} />
        <mesh geometry={nodes.Cube034_130.geometry} material={materials['Material.798']} />
        <mesh geometry={nodes.Cube034_131.geometry} material={materials['Material.801']} />
        <mesh geometry={nodes.Cube034_132.geometry} material={materials['Material.804']} />
        <mesh geometry={nodes.Cube034_133.geometry} material={materials['Material.803']} />
        <mesh geometry={nodes.Cube034_134.geometry} material={materials['Material.805']} />
        <mesh geometry={nodes.Cube034_135.geometry} material={materials['Material.802']} />
        <mesh geometry={nodes.Cube034_136.geometry} material={materials['Material.812']} />
        <mesh geometry={nodes.Cube034_137.geometry} material={materials['Material.811']} />
        <mesh geometry={nodes.Cube034_138.geometry} material={materials['Material.813']} />
        <mesh geometry={nodes.Cube034_139.geometry} material={materials['Material.810']} />
        <mesh geometry={nodes.Cube034_140.geometry} material={materials['Material.807']} />
        <mesh geometry={nodes.Cube034_141.geometry} material={materials['Material.808']} />
        <mesh geometry={nodes.Cube034_142.geometry} material={materials['Material.806']} />
        <mesh geometry={nodes.Cube034_143.geometry} material={materials['Material.809']} />
        <mesh geometry={nodes.Cube034_144.geometry} material={materials['Material.828']} />
        <mesh geometry={nodes.Cube034_145.geometry} material={materials['Material.827']} />
        <mesh geometry={nodes.Cube034_146.geometry} material={materials['Material.829']} />
        <mesh geometry={nodes.Cube034_147.geometry} material={materials['Material.826']} />
        <mesh geometry={nodes.Cube034_148.geometry} material={materials['Material.823']} />
        <mesh geometry={nodes.Cube034_149.geometry} material={materials['Material.824']} />
        <mesh geometry={nodes.Cube034_150.geometry} material={materials['Material.822']} />
        <mesh geometry={nodes.Cube034_151.geometry} material={materials['Material.825']} />
        <mesh geometry={nodes.Cube034_152.geometry} material={materials['Material.815']} />
        <mesh geometry={nodes.Cube034_153.geometry} material={materials['Material.816']} />
        <mesh geometry={nodes.Cube034_154.geometry} material={materials['Material.814']} />
        <mesh geometry={nodes.Cube034_155.geometry} material={materials['Material.817']} />
        <mesh geometry={nodes.Cube034_156.geometry} material={materials['Material.820']} />
        <mesh geometry={nodes.Cube034_157.geometry} material={materials['Material.819']} />
        <mesh geometry={nodes.Cube034_158.geometry} material={materials['Material.821']} />
        <mesh geometry={nodes.Cube034_159.geometry} material={materials['Material.818']} />
        <mesh geometry={nodes.Cube034_160.geometry} material={materials['Material.860']} />
        <mesh geometry={nodes.Cube034_161.geometry} material={materials['Material.859']} />
        <mesh geometry={nodes.Cube034_162.geometry} material={materials['Material.861']} />
        <mesh geometry={nodes.Cube034_163.geometry} material={materials['Material.858']} />
        <mesh geometry={nodes.Cube034_164.geometry} material={materials['Material.855']} />
        <mesh geometry={nodes.Cube034_165.geometry} material={materials['Material.856']} />
        <mesh geometry={nodes.Cube034_166.geometry} material={materials['Material.854']} />
        <mesh geometry={nodes.Cube034_167.geometry} material={materials['Material.857']} />
        <mesh geometry={nodes.Cube034_168.geometry} material={materials['Material.847']} />
        <mesh geometry={nodes.Cube034_169.geometry} material={materials['Material.848']} />
        <mesh geometry={nodes.Cube034_170.geometry} material={materials['Material.846']} />
        <mesh geometry={nodes.Cube034_171.geometry} material={materials['Material.849']} />
        <mesh geometry={nodes.Cube034_172.geometry} material={materials['Material.852']} />
        <mesh geometry={nodes.Cube034_173.geometry} material={materials['Material.851']} />
        <mesh geometry={nodes.Cube034_174.geometry} material={materials['Material.853']} />
        <mesh geometry={nodes.Cube034_175.geometry} material={materials['Material.850']} />
        <mesh geometry={nodes.Cube034_176.geometry} material={materials['Material.831']} />
        <mesh geometry={nodes.Cube034_177.geometry} material={materials['Material.832']} />
        <mesh geometry={nodes.Cube034_178.geometry} material={materials['Material.830']} />
        <mesh geometry={nodes.Cube034_179.geometry} material={materials['Material.833']} />
        <mesh geometry={nodes.Cube034_180.geometry} material={materials['Material.836']} />
        <mesh geometry={nodes.Cube034_181.geometry} material={materials['Material.835']} />
        <mesh geometry={nodes.Cube034_182.geometry} material={materials['Material.837']} />
        <mesh geometry={nodes.Cube034_183.geometry} material={materials['Material.834']} />
        <mesh geometry={nodes.Cube034_184.geometry} material={materials['Material.844']} />
        <mesh geometry={nodes.Cube034_185.geometry} material={materials['Material.843']} />
        <mesh geometry={nodes.Cube034_186.geometry} material={materials['Material.845']} />
        <mesh geometry={nodes.Cube034_187.geometry} material={materials['Material.842']} />
        <mesh geometry={nodes.Cube034_188.geometry} material={materials['Material.839']} />
        <mesh geometry={nodes.Cube034_189.geometry} material={materials['Material.840']} />
        <mesh geometry={nodes.Cube034_190.geometry} material={materials['Material.838']} />
        <mesh geometry={nodes.Cube034_191.geometry} material={materials['Material.841']} />
      </group>
      <mesh geometry={nodes.Icosphere.geometry} material={materials.Glow} position={[-6.46, 3.94, -15.53]} />
      <mesh geometry={nodes.Emitter.geometry} material={materials.Transparent} position={[-6.46, 2.64, -15.53]} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Ember.002']} position={[-6.59, 2.93, -15.62]} scale={0.62} />
    </group>
  )
}

useGLTF.preload('/Campsite.glb')

export default function App() {
  return (
    <>
      <div className="bg" />
      <h1>
        Sean <span style={{ fontSize: '0.4em' }}></span>
        <br />
        <span>Simms</span>
      </h1>
      <Canvas dpr={[1.5, 2]} linear shadows>
        <fog attach="fog" args={['#272730', 48, 60]} />
        <ambientLight intensity={0.75} />
        <PerspectiveCamera makeDefault position={[50, -20, 20]} fov={75}>
          <pointLight intensity={2} position={[20, 100, 0]} />
          <spotLight castShadow intensity={2.25} angle={0.2} penumbra={1} position={[-25, 20, -15]} shadow-mapSize={[1024, 1024]} shadow-bias={-0.0001} />
        </PerspectiveCamera>
        <Suspense fallback={null}>
          <Model url="/scene.glb" position={[1, -10, 0]} />
        </Suspense>
        <OrbitControls autoRotate enablePan={false} enableZoom={false} maxPolarAngle={Math.PI / 2} minPolarAngle={Math.PI / 2} />
        <Stars radius={500} depth={50} count={1000} factor={10} />
      </Canvas>
      <div className="layer" />
      <Loader />

      <a href="https://www.linkedin.com/in/sean-simms-29599116b/" className="bottom-right1" children="LinkedIn" />
    </>
  )
}
